### PR TITLE
Fix/parse time or error60

### LINKED ISSUE #41: parseTimeOrError: no parse of "2020-02-24 11:60" (since LTS-15.1 migration)
Since upgrading to LTS-15.1 (which ships GHC 8.8.2), I experienced troubles with some scheduled jobs that are triggered every hour. 
I get the following exception: 
```
stacktrace-exe: parseTimeOrError: no parse of "2020-02-24 11:60"
CallStack (from HasCallStack):
  error, called at libraries/time/lib/Data/Time/Format/Parse.hs:82:12 in time-1.9.3:Data.Time.Format.Parse
```
The full stacktrace: 
```
*** Exception (reporting due to +RTS -xc): (THUNK_2_0), stack trace: 
  System.Cron.Schedule.readTime',
  called from System.Cron.Schedule.findNextMinuteDelay.next,
  called from System.Cron.Schedule.findNextMinuteDelay,
  called from System.Cron.Schedule.forkJob,
  called from System.Cron.Schedule.execSchedule,
  called from Main.main
stacktrace-exe: parseTimeOrError: no parse of "2020-02-24 11:60"
CallStack (from HasCallStack):
  error, called at libraries/time/lib/Data/Time/Format/Parse.hs:82:12 in time-1.9.3:Data.Time.Format.Parse
```

I managed to reproduce the issue starting a project from scratch (with a `stack init`) as below: 

```haskell
main :: IO ()
main = do
  let Right cs1 = parseCronSchedule everyHour
  print $ describe defaultOpts cs1
  tids <- execSchedule $ addJob job1 everyHour
  print tids
  _ <- getLine
  pure ()

job1 :: IO ()
job1 = do
  currentTime <- getCurrentTime
  print currentTime

everyHour :: Text
everyHour = pack "0 * * * *"
```

For the record, the job ran fine before upgrading to LTS-15.1. 
Do you have any idea about it?

Thank you in advance!

### PR DESCRIPTION
**Pull request by Sir4ur0n**
Here is the PR. I tried as much as possible to stick to the style of the lib (which doesn't seem to use Hindent or Ormolu, but seems to use Stylish Haskell for import formatting).
I am also not a library author (I'm more of an application author) so there may be best/bad practices I am not aware of, feel free to pinpoint them!

* Add LTS 15 to Travis CI
* Cleanup `stack.yaml` and provide LTS-13 specific Stack file
* Isolate business logic from IO for next minute
* Add unit and property tests to business code for next minute (which pass on LTS 14 but fail on LTS 15 for the same reason as #41)
* Remove the CPP pragma and condition as all used functions are available in `time-1.4.0` which is the lower bound in the Cabal dependencies
* Clean some minor Hlint warnings

Closes #41

### CODE REVIEW

**Comment by Sir4ur0n** [comment]
@MichaelXavier here it is!

**Comment by Sir4ur0n** [comment]
I forgot to mention, maybe this will reassure some: in the meantime we have shipped this PR on our platforms (our `stack.yaml` targets my fork), and it fixes the issue, everything else seems to work fine.

**Comment by Sir4ur0n** [comment]
@MichaelXavier I think I finally fixed the build :disappointed: 

Basically I noticed you had frozen the Hedhehog version - I assume because it wasn't there in LTS 13 - but the referenced version is no longer possible for LTS 15.
So I changed the build logic slightly: there is a dedicated Stack file for LTS 13 and another one - more standard - for all other LTSes.

Thus I removed the cache on `.stack-work` as it sometimes uses the LTS 13 cache for others and vice-versa.
Also, caching on `.stack-work` doesn't have much impact on build/test/bench time.

Let me know if it's ok for you!

**Comment by Sir4ur0n** [comment]
@MichaelXavier sorry to bump, but do you think you could take some time to review this PR please?

Thank you!

**Comment by MichaelXavier** [comment]
Looks great! Sorry for the delay, this slipped my mind. This is released as 0.7.0. Thanks for taking care of this.

**Comment by Sir4ur0n** [comment]
Thank you very much!

I noticed the documentation is not published on the Hackage page, is there something we can do about it?
https://hackage.haskell.org/package/cron-0.7.0

**Comment by paolino** [comment]
it takes a while to be processed

**Comment by Sir4ur0n** [comment]
Perfect, thank you, it's now available 😄

**Comment by MichaelXavier** [comment]
I think it gets generated eventually?

**Pull request merged**
