### PR TITLE
Accumulated PR changes

### PR DESCRIPTION
**Pull request by avanov**
Hi! I needed cron on GHC 9.6, and I made a fork with a few previous PR's in the original repository merged in my branch. This is useful for those who want all of them in a single source distribution available for Cabal repository overrides in their projects.

### CODE REVIEW

**Comment by domenkozar** [comment]
ping @MichaelXavier

**Comment by MichaelXavier** [comment]
@avanov @domenkozar Really sorry about the neglect here. I turned off Github notifications for a while and I'm trying to get ahold of them now. The package is uploaded to hackage now.

**Comment by domenkozar** [comment]
Thank you!

**Comment by avanov** [comment]
@MichaelXavier thank you, and no worries re. the timing!

**Pull request merged**
